language: node_js
env: CI
node_js:
  - '0.12'
  - '0.11'
  - '0.10'
  - 'iojs'
before_script:
  - npm install -g yo bower gulp

install: gulp cordova-install
script: gulp build

after_script:
  - npm run coveralls
notifications:
  email: true
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9999ad90386ac16bb300
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
