language: node_js
node_js:
  - '0.10'
install: gulp cordova-install
script: gulp build
after_script:
  - npm run coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9999ad90386ac16bb300
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
